- name: variables to print
  hosts: web
  vars:
   COURSE: "DevOps with AWS"
   DURATION: "120hrs"
   TRAINER: "Sivakumar reddy"
  tasks:
  - name: print the information
    vars:
     COURSE: "Ansible"
     DURATION: "120hrs"
     TRAINER: "Sivakumar reddy"
    ansible.builtin.debug:
     msg: " Hi Iam learning {{COURSE}} and duration is {{DURATION}} and trainer is {{TRAINER}}"