- name: variables to print
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: please enter your course name
  - name: TRAINER
    prompt: please enter your trainer name
  - name: DURATION
    prompt: please enter your course duration
  tasks:
  - name: print the information
    ansible.builtin.debug:
     msg: " Hi Iam learning {{COURSE}} and duration is {{DURATION}} and trainer is {{TRAINER}}"