- name: install nginx
  become: yes
  hosts: web
  tasks:
  - name: print the stats
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"

  - name: Install nginx in redhat 
    ansible.builtin.dnf:
     name: nginx
     state: present
    when: ansible_os_family == "Redhat"

  - name: Install nginx in Debian
    ansible.builtin.apt:
     name: nginx
     state: present
    when: ansible_os_family == "Debian"