- name: Install packages
  hosts: local
  tasks:
  - name: Install packages
    ansible.builtin.package:
     name: "{{item}}"
     state: present
    loop:
    - mysql
    - nginx
    - postfix
    - httpd
