- name: demo on functions/filters
  hosts: local
  connection: local
  tasks: 
  - name: print the default variable
    ansible.builtin.debug:
     msg: "Hello {{ course | default ('Ansible') }}"

  - name: convert to uppercase
    vars:
     greeting: "Hello Ramesh"
    ansible.builtin.debug:
     msg: " {{ greeting | lower }} "

  - name: convert to uppercase
    vars:
     greeting: "Hello Ramesh"
    ansible.builtin.debug:
     msg: " {{ greeting | upper }} "

  - name: convert to uppercase
    vars:
     numbers: [1,2,3,45,4,5,3,5,4]
    ansible.builtin.debug:
     msg: " {{ numbers | unique }} "

