- name: demo on functions/filters
  hosts: local
  connection: local
  tasks: 
  - name: print the default variable
    ansible.builtin.debug:
     msg: "Hello {{ course | default ('Ansible') }}"

  - name: convert to uppercase
    vars:
     gretting: "Hello Ramesh"
    ansible.builtin.debug:
     msg: " {{ greeting | lower }} "

  - name: convert to uppercase
    vars:
     gretting: "Hello Ramesh"
    ansible.builtin.debug:
     msg: " {{ greeting | upper }} "

