- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
   subnet_id: "subnet-0cb5f65d37fd48e90" # replace with your subnet id
   sg_id: "sg-0e12349e784c6ec0a"
   ami_id: "ami-09c813fb71547fc4f"
   instances:
   - mysql 
   - backend
   - frontend
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
     name: "{{ item }}"
     vpc_subnet_id: " {{ subnet_id }}"
     instance_type: "t3.micro"
     security_group: " {{ sg_id }}"
     image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances
  
    
