- name: create ec2 and r53 records
  hosts: local
  connection: local
  # assignment
  # move this to vars_files
  vars:
    subnet_id: "subnet-0cb5f65d37fd48e90" # replace with your subnet id
    sg_id: "sg-0e12349e784c6ec0a"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
    zone: sivadevops.fun
  tasks:
  - name: ansible to install boto3 and botocore
    ansible.builtin.pip:
      name:
      - boto3
      - botocore
      executable: pip3.9
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"

  # - name: create route-53 private records
  #   amazon.aws.route53:
  #    state: present
  #    zone: "{{ zone }}"
  #    record: 
  #    type: A
  #    ttl: 1
  #    value: 
  #    wait: true
  #    overwrite: true
  #   loop: 

  
    
